
let POSTS=[]; let activeTheme=''; let featuredOnly=false; let activeSlug='';
const $=id=>document.getElementById(id);
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function filtered(){const term=($('search').value||'').toLowerCase(); return POSTS.filter(p=>(!activeTheme||p.themes.includes(activeTheme))&&(!featuredOnly||p.featured)&&(!term||(p.title+' '+p.excerpt+' '+p.themes.join(' ')+' '+p.categories.join(' ')).toLowerCase().includes(term))).sort((a,b)=>(b.featured-a.featured)||String(b.date).localeCompare(String(a.date))||a.title.localeCompare(b.title));}
function renderList(){const arr=filtered(); $('count').textContent=`${arr.length} / ${POSTS.length}`; $('navList').innerHTML=arr.map(p=>`<div class="nav-item ${p.slug===activeSlug?'active':''}" data-slug="${esc(p.slug)}"><div class="nav-title">${p.featured?'<span class="star">★</span>':''}${esc(p.title)}</div><div class="nav-meta">${esc(p.date)} · ${p.word_count} words</div></div>`).join(''); document.querySelectorAll('.nav-item').forEach(el=>el.addEventListener('click',()=>openPost(el.dataset.slug))); document.querySelectorAll('.chip').forEach(c=>c.classList.toggle('active', c.dataset.theme===activeTheme));}
function renderCards(){const arr=filtered(); $('homeCards').innerHTML=arr.slice(0,60).map(p=>`<div class="card ${p.featured?'featured':''}" data-slug="${esc(p.slug)}"><h3>${p.featured?'★ ':''}${esc(p.title)}</h3><div class="meta-row"><span class="pill">${esc(p.date)}</span><span class="pill">${p.word_count} words</span>${p.themes.map(t=>`<span class="tag theme">${esc(t)}</span>`).join('')}</div><div class="excerpt">${esc(p.excerpt)}</div></div>`).join(''); document.querySelectorAll('.card[data-slug]').forEach(el=>el.addEventListener('click',()=>openPost(el.dataset.slug)));}
function renderThemes(){const themes=[...new Set(POSTS.flatMap(p=>p.themes))].sort(); $('themes').innerHTML=themes.map(t=>`<button class="chip" data-theme="${esc(t)}">${esc(t)}</button>`).join(''); document.querySelectorAll('.chip').forEach(b=>b.addEventListener('click',()=>{activeTheme=activeTheme===b.dataset.theme?'':b.dataset.theme; featuredOnly=false; renderList(); renderCards();}));}
async function openPost(slug){const p=POSTS.find(x=>x.slug===slug); if(!p)return; activeSlug=slug; renderList(); const res=await fetch(`content/${slug}.html`); const text=await res.text(); const doc=new DOMParser().parseFromString(text,'text/html'); const article=doc.querySelector('.reader')||doc.querySelector('article')||doc.body; $('main').innerHTML=article.outerHTML; history.replaceState(null,'',`#${slug}`); $('main').scrollTop=0;}
function showHome(){activeSlug=''; history.replaceState(null,'',location.pathname); renderList(); $('main').innerHTML=document.getElementById('homeTemplate').innerHTML; renderCards();}
function showFeatured(){featuredOnly=true; activeTheme=''; renderList(); renderCards();}
function resetFilters(){featuredOnly=false; activeTheme=''; $('search').value=''; renderList(); renderCards();}
async function init(){const res=await fetch('data/posts.json'); POSTS=await res.json(); $('totalPosts').textContent=POSTS.length; $('featuredCount').textContent=POSTS.filter(p=>p.featured).length; renderThemes(); $('search').addEventListener('input',()=>{featuredOnly=false;renderList();renderCards();}); $('homeBtn').addEventListener('click',showHome); $('featuredBtn').addEventListener('click',showFeatured); $('resetBtn').addEventListener('click',resetFilters); showHome(); if(location.hash.length>1){openPost(location.hash.slice(1));}}
init().catch(err=>{console.error(err); $('main').innerHTML='<div class="reader"><h1>Loading error</h1><p>'+esc(err.message)+'</p></div>';});
